title: International Workshop on Big Data Reduction
description: held with 2020 IEEE International Conference on Big Data
theme: jekyll-theme-slate
show_downloads: false
google_analytics: UA-97217045-4
github:
  is_project_page: false
